version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/docs"
    groups:
      docusaurus:
        patterns:
          - "*docusaurus*"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      aws-dependencies:
        patterns:
          - AWSSDK*
          - awssdk*
      azure-dependencies:
        patterns:
          - Azure*
      test-dependencies:
        patterns:
          - NUnit*
          - "*Test*"
    ignore:
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.CodeAnalysis*"
      - dependency-name: "Microsoft.Build"
